### ISSUE TITLE
Front end framework choice 

### ISSUE THREAD

**Issue by Sanel-V** [s-dominik/TeamFinder#2]
Hey,

We've been informed that choosing a front end framework to ease the workflow is highly recommended.
From what I've researched we have three popular choices with a healthy amount of tutorials, documentation and help:
1.  React
2. Vue
3. Angular

Look them up and make a choice. We don't have much time left, so please choose on a short notice

**Comment by JonasEszter** [comment]
Hey,

After a long discussion, we have been decided to use React.js, because it's more easier than Angular and one of the frontend developer already have some knowledge about this programming language.
